name: Test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      # Read Golang from go.mod
      - name: Read Go version from go.mod
        id: read_go_version
        run: |
          go_version=$(grep -oP '(?<=^go )\d+\.\d+' go.mod)
          echo "go_version=$go_version" >> $GITHUB_ENV
      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}
      # Test go 
      - name: Test Go
        run: |
          go test ./... -v -coverprofile=coverage.out
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}